name = "DynamicMovementPrimitives"
uuid = "c3fee2e9-8015-57de-85e5-c840d3ed97ec"
authors = ["Fredrik Bagge Carlson"]
version = "0.4.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
OrdinaryDiffEq = "6"
RecipesBase = "1"
Requires = "1"
julia = "1"


[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Plots"]
